name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./src

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
      MONGODB_DATABASE_NAME: ${{ vars.MONGODB_DATABASE_NAME }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Go Generate
        run: go generate -v ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Upload Sequence Diagrams
        uses: actions/upload-artifact@v3
        with:
          name: sequence-diagrams
          path: ./src/.sequence/
